GleamTech.Util.Language.name = "en";
GleamTech.Util.Language.entries = {
    "500": "Welcome to {0}"
    , "501": "Please enter your credentials:"
    , "502": "User name:"
    , "503": "Password:"
    , "504": "Login"
    , "505": "Login failed:"
    , "Label.DisplayLanguage": "Display language"
    , "Label.FormatLanguage": "Format language"
    , "506": "Users"
    , "507": "Groups"
    , "508": "Root Folders"
    , "509": "Name"
    , "510": "Full Name"
    , "511": "Login Count"
    , "512": "Last Login Time"
    , "513": "Date Created"
    , "514": "Date Modified"
    , "515": "Members"
    , "516": "Location"
    , "517": "Cannot delete a user which is member of the Administrators group!"
    , "518": "You can not delete a root folder in Demo Mode!"
    , "519": "You can not rename administrator in Demo Mode!"
    , "520": "User or group with this name already exists!"
    , "521": "You can not rename a root folder in Demo Mode!"
    , "522": "Root folder with this name already exists!"
    , "523": "Invalid user name or password!"
    , "525": "Please contact the administrator."
    , "526": "This user is disabled!"
    , "527": "{0} users"
    , "528": "{0} groups"
    , "529": "{0} root folders"
    , "530": "Back to Folder Browsing"
    , "531": "License Information"
    , "FileVista.Action.Logout": "Log out"
    , "533": "New User"
    , "534": "Refresh"
    , "535": "Select All"
    , "536": "Invert Selection"
    , "537": "Delete"
    , "538": "Rename"
    , "539": "Properties"
    , "540": "New Group"
    , "541": "New Root Folder"
    , "542": "Tasks"
    , "543": "There was a problem retrieving the XML data:"
    , "544": "An error occured:"
    , "545": "Edit User"
    , "546": "Edit Group"
    , "547": "Edit Root Folder"
    , "548": "Are you sure you want to delete '{0}'?"
    , "549": "Enter a new name for the item:"
    , "FileVista.Action.Administration": "Administration"
    , "551": "OK"
    , "552": "Cancel"
    , "553": "Prompt"
    , "554": "Session has expired, please login again."
    , "555": "You are not allowed to view this page!"
    , "556": "Name:"
    , "557": "Description"
    , "558": "Member users:"
    , "559": "Permissions"
    , "560": "Select users"
    , "561": "Search criteria:"
    , "562": "Search results:"
    , "563": "Add"
    , "564": "Remove"
    , "565": "Select"
    , "566": "Find Now"
    , "567": "Group Manager"
    , "568": "Please fill in 'Name' field!"
    , "569": "Location:"
    , "570": "Groups or users:"
    , "571": "Quota"
    , "572": "Select groups or users"
    , "573": "Search for:"
    , "574": "All"
    , "FileVista.Permission.ListSubfolders": "List subfolders"
    , "FileVista.Permission.ListFiles": "List files"
    , "FileVista.Permission.Create": "Create"
    , "FileVista.Permission.Delete": "Delete"
    , "FileVista.Permission.Rename": "Rename"
    , "FileVista.Permission.Edit": "Edit"
    , "FileVista.Permission.Upload": "Upload"
    , "FileVista.Permission.Download": "Download"
    , "FileVista.Permission.Compress": "Compress"
    , "FileVista.Permission.Extract": "Extract"
    , "FileVista.Permission.Cut": "Cut"
    , "FileVista.Permission.Copy": "Copy"
    , "FileVista.Permission.Paste": "Paste"
    , "FileVista.Permission.Preview": "Preview"
    , "FileVista.Permission.Print": "Print"
    , "FileVista.Permission.CreatePublicLink": "Create public link"
    , "588": "Do not limit disk usage"
    , "589": "Limit disk space to"
    , "590": "Please fill in 'Location' field!"
    , "591": "You can not create a Root Folder in Demo Mode!"
    , "Message.Error.FeatureTests": "You can not edit \"Feature Tests\" root folder in Demo Mode!"
    , "593": "User name:"
    , "594": "Full name:"
    , "595": "Email:"
    , "596": "Confirm Password:"
    , "597": "Password never expires"
    , "598": "User cannot change password"
    , "599": "User must change password at next login"
    , "600": "Account is disabled"
    , "601": "Account is locked out"
    , "602": "Change password"
    , "603": "Please fill in 'User name' field!"
    , "604": "Email is in wrong format!"
    , "605": "Passwords don't match!"
    , "606": "Please fill in 'Password' field!"
    , "607": "You can not update Administrator user in Demo Mode!"
    , "608": "License does not allow more users to be added!"
    , "609": "Licensed to:"
    , "610": "License type:"
    , "611": "Purchase date:"
    , "612": "Apply a new license key"
    , "613": "Would you like to upgrade your license?"
    , "614": "This license key is not valid!"
    , "615": "Events"
    , "616": "Type"
    , "617": "Date"
    , "618": "Time"
    , "619": "User"
    , "FileVista.Event.Login": "Login"
    , "FileVista.Event.Logout": "Logout"
    , "FileVista.Event.Failure": "Failure"
    , "FileVista.Event.Browse": "Browse"
    , "FileVista.Event.Create": "Create"
    , "FileVista.Event.Delete": "Delete"
    , "FileVista.Event.Rename": "Rename"
    , "FileVista.Event.Copy": "Copy"
    , "FileVista.Event.Move": "Move"
    , "FileVista.Event.Compress": "Compress"
    , "FileVista.Event.Extract": "Extract"
    , "FileVista.Event.Upload": "Upload"
    , "FileVista.Event.Download": "Download"
    , "FileVista.Event.Preview": "Preview"
    , "FileVista.Event.PublicLink": "Public Link"
    , "FileVista.EventSet.All": "All"
    , "633": "You cannot delete your own account!"
    , "634": "User is not deleted because of other memberships. Only membership of this group is removed."
    , "635": "{0} events"
    , "636": "Application Settings"
    , "637": "Event types"
    , "639": "Log Events"
    , "640": "You can not save settings in Demo Mode!"
    , "641": "Log size"
    , "642": "Maximum log size:"
    , "643": "When maximum log size is reached:"
    , "644": "Delete events older than {0} days"
    , "645": "Filter"
    , "646": "Event Properties"
    , "647": "Date Range"
    , "648": "Clear Log"
    , "649": "Are you sure you want to clear event log?"
    , "FileVista.Action.UserSettings": "User Settings"
    , "652": "Remember me"
    , "653": "User is locked out for too many invalid login attempts!"
    , "654": "Passwords will expire after {0} days"
    , "655": "Users will be locked out after {0} invalid login attempts"
    , "656": "Access Control for"
    , "657": "Inherit from parent"
    , "658": "File types"
    , "659": "Do not restrict file types"
    , "660": "Restrict file types"
    , "661": "Administrators group should contain at least one administrator!"
    , "662": "Administrators group can not be deleted!"
    , "663": "Cannot rename a user which is member of the Administrators group!"
    , "664": "Language"
    , "665": "Notifications"
    , "666": "{0} Event Notification - {1}"
    , "667": "An event has occured in a folder that you ({0}) were set to receive notifications from. The event details are listed below."
    , "668": "Upload methods"
    , "669": "Show file extensions"
    , "670": "Show system type descriptions"
    , "671": "Show hidden files and folders"
    , "672": "Show system files and folders"
    , "673": "Disable folder expandable check"
    , "674": "Maximum allowed size to compress (per action)"
    , "675": "Temporary files location"
    , "676": "General"
    , "677": "Folder Browsing"
    , "678": "Logging"
    , "679": "Email"
    , "680": "The temporary files location does not exist or does not have write permission!"
    , "681": "Send email notifications"
    , "682": "From email address"
    , "FileVista.Label.SmtpHost": "SMTP host"
    , "FileVista.Label.SmtpPort": "SMTP port"
    , "FileVista.Label.SmtpAuthentication": "SMTP authentication"
    , "686": "Anonymous"
    , "687": "Use Windows credentials"
    , "688": "Use below credentials"
    , "689": "Use SSL"
    , "FileVista.Action.TestEmail": "Test Email"
    , "692": "Open linked file in the browser"
    , "693": "Link expires in {0} days"
    , "694": "Link can be opened only {0} times"
    , "695": "Protect link with password"
    , "696": "Use custom name in link"
    , "697": "Advanced"
    , "FileVista.Label.Create": "Create"
    , "FileVista.Label.Update": "Update"
    , "700": "Test"
    , "701": "Email"
    , "703": "Please contact the link owner for more information."
    , "704": "Link not found"
    , "705": "The link you requested cannot be found or no longer exists. The link owner may have deleted the link."
    , "706": "Resource not found"
    , "707": "The resource that was linked to, cannot be found or no longer exists. The link owner may have deleted or moved the target resource."
    , "708": "Link has expired"
    , "709": "The link you requested has expired due to the expiration time limit set by the link owner."
    , "710": "Link limit has been reached"
    , "711": "The link you requested has reached the maximum opening limit set by the link owner."
    , "712": "Link is disabled"
    , "713": "The link you requested is disabled by the link owner."
    , "714": "Password required"
    , "715": "The link you requested is protected with a password set by the link owner."
    , "716": "Please enter the password you were supplied by the link owner."
    , "717": "Invalid password!"
    , "718": "Anonymous User"
    , "720": "Trial license mode (5 users) - {0} days left"
    , "721": "Purchased license mode"
    , "722": "Purchase new license"
    , "723": "Upgrade existing license"
    , "724": "Override base url"
    , "725": "Limit the number of members to"
    , "726": "Group settings does not allow more users to be added!"
    , "FileVista.Label.LoggedInAs": "Logged in as {0}"
    , "FileVista.Label.SectionUnavailable": "This section is unavailable."
    , "FileVista.Label.SectionEmpty": "This section is empty."
    , "FileVista.Action.Connect": "Connect"
    , "FileVista.Label.Filtered": "Filtered"
    , "FileVista.Label.Allow": "Allow"
    , "FileVista.Label.Deny": "Deny"
    , "FileVista.Label.Notify": "Notify"
    , "FileVista.Label.DoNotNotify": "Do not notify"
    , "FileVista.PermissionSet.Full": "Full"
    , "FileVista.PermissionSet.Read": "Read"
    , "FileVista.NotificationSet.OnAll": "On all"
    , "FileVista.Notification.OnFailure": "On failure"
    , "FileVista.Notification.OnBrowse": "On browse"
    , "FileVista.Notification.OnCreate": "On create"
    , "FileVista.Notification.OnDelete": "On delete"
    , "FileVista.Notification.OnRename": "On rename"
    , "FileVista.Notification.OnCopy": "On copy"
    , "FileVista.Notification.OnMove": "On move"
    , "FileVista.Notification.OnCompress": "On compress"
    , "FileVista.Notification.OnExtract": "On extract"
    , "FileVista.Notification.OnUpload": "On upload"
    , "FileVista.Notification.OnDownload": "On download"
    , "FileVista.Notification.OnPreview": "On preview"
    , "FileVista.Prompt.AddFileType": "Enter a file type pattern:"
    , "FileVista.Error.InvalidFileType": "A file type pattern can not contain any of the following characters:"
    , "FileVista.Prompt.RemoveInheritance": "\r\n      If you proceed, inheritable parent entries will no longer propagate to this folder.\r\n\r\n      - Click Add to convert and add inherited parent entries as explicit entries on this folder.\r\n\r\n      - Click Remove to remove inherited parent entries from this folder.\r\n\r\n      - Click Cancel if you do not want to modify inheritance settings at this time.\r\n    "
    , "FileVista.Label.IncludePathInLink": "Include path in link:"
    , "FileVista.Label.NameInLink": "Name in link:"
    , "FileVista.Label.Delete": "Delete"
    , "FileVista.Label.PublicLink": "Public Link"
    , "FileVista.Label.PublicLinks": "Public Links"
    , "FileVista.Label.LinkedItem": "Linked Item"
    , "FileVista.Label.HitCount": "Hit Count"
    , "FileVista.Label.LastHitTime": "Last Hit Time"
    , "FileVista.Label.Expiration": "Expiration"
    , "FileVista.Label.HitLimit": "Hit Limit"
    , "FileVista.Label.CreatedBy": "Created By"
    , "FileVista.Label.PublicLinksCount": "{0} public links"
    , "FileVista.Label.Expired": "Expired"
    , "FileVista.Label.NotExpired": "Not Expired"
    , "FileVista.Label.Reached": "Reached"
    , "FileVista.Label.NotReached": "Not Reached"
    , "FileVista.Label.Close": "Close"
    , "Label.Share.Verb": "Share"
    , "Label.CreatePublicLink": "Create public link..."
    , "Label.ManagePublicLinks": "Manage public links..."
    , "Label.PublicLinksFor": "Public links for {0}"
    , "Label.NewPublicLink": "New Public Link"
    , "Label.EditPublicLink": "Edit Public Link"
    , "FileVista.Label.EmailDeliveryMethod": "Email delivery method"
    , "FileVista.Label.SmtpServer": "SMTP server"
    , "FileVista.Label.SpecifiedPickupDirectory": "Specified pickup directory"
    , "FileVista.Label.PickupDirectoryFromIis": "Pickup directory from IIS"
    , "FileVista.Label.PickupDirectoryLocation": "Pickup directory location"
    , "FileVista.Action.Up": "Up"
    , "FileVista.Action.Down": "Down"
    , "Label.ViewLayout": "View layout"
    , "Label.DownloadWithChunkedTransferThreshold": "Download with chunked transfer threshold (eg. 2GB for Microsoft Forefront UAG)"
    , "Label.ImportUsers": "Import Users"
    , "Label.DownloadOnDoubleClick": "Download on double-click"
    , "Label.ExcludedExtensionsForPreview": "Excluded extensions for preview (comma separated)"
    , "Label.MaximumPublicLinkAge": "Maximum public link age"
    , "Label.MaximumPublicLinkHits": "Maximum public link hits"
    , "Label.Days": "{0} days"
    , "Message.LinkHasExpiredPolicy": "The link you requested has expired due to the maximum age policy set by the administrator."
    , "Message.LinkLimitReachedPolicy": "The link you requested has reached the maximum hits policy set by the the administrator."
    , "Message.ContactAdministrator": "Please contact the administrator for more information."
    , "Label.About": "About FileVista"
    , "Label.View.Noun": "View"
    , "Label.Panes": "Panes"
    , "Label.NavigationPane": "Navigation pane"
    , "Label.PreviewPane": "Preview pane"
    , "Label.DetailsPane": "Details pane"
    , "Label.Layout": "Layout"
    , "Label.Layout.ExtraLargeIcons": "Extra large icons"
    , "Label.Layout.LargeIcons": "Large icons"
    , "Label.Layout.MediumIcons": "Medium icons"
    , "Label.Layout.SmallIcons": "Small icons"
    , "Label.Layout.List": "List"
    , "Label.Layout.Details": "Details"
    , "Label.Layout.Tiles": "Tiles"
    , "Label.Layout.Content": "Content"
    , "Label.Home": "Home"
    , "Label.Select": "Select"
    , "Label.SelectAll": "Select all"
    , "Label.SelectNone": "Select none"
    , "Label.InvertSelection": "Invert selection"
    , "Label.ShowHide": "Show/hide"
    , "Label.ItemCheckBoxes": "Item check boxes"
    , "Message.EmptyView": "This view is empty."
    , "Label.ItemCount": "{0} item"
    , "Label.ItemsCount": "{0} items"
    , "Label.SelectedItemCount": "{0} item selected"
    , "Label.SelectedItemsCount": "{0} items selected"
    , "Label.Refresh.Verb": "Refresh"
    , "Label.Expand": "Expand"
    , "Label.Collapse": "Collapse"
    , "Label.OK": "OK"
    , "Label.Yes": "Yes"
    , "Label.No": "No"
    , "Label.Cancel": "Cancel"
    , "Label.Close": "Close"
    , "Label.SearchSelected": "Search {0}"
    , "Label.Clipboard": "Clipboard"
    , "Label.Cut.Verb": "Cut"
    , "Label.Copy.Verb": "Copy"
    , "Label.Paste.Verb": "Paste"
    , "Label.Organize": "Organize"
    , "Label.Delete": "Delete"
    , "Label.Rename": "Rename"
    , "Label.New": "New"
    , "Label.NewFolder": "New folder"
    , "Label.NewFile": "New file"
    , "Label.Transfer.Verb": "Transfer"
    , "Label.Download.Verb": "Download"
    , "Label.Upload.Verb": "Upload"
    , "Label.Compression": "Compression"
    , "Label.AddToZip": "Add to zip..."
    , "Label.ExtractAll": "Extract all"
    , "Label.ExtractAllTo": "Extract all to..."
    , "Label.ExtractAllHere": "Extract all here"
    , "Label.Open.Verb": "Open"
    , "Label.Preview.Verb": "Preview"
    , "Label.DeleteFile": "Delete File"
    , "Message.Confirm.DeleteFile": "Are you sure you want to delete this file?"
    , "Label.DeleteFolder": "Delete Folder"
    , "Message.Confirm.DeleteFolder": "Are you sure you want to delete this folder?"
    , "Label.DeleteMultipleItems": "Delete Multiple Items"
    , "Message.Confirm.DeleteMultipleItems": "Are you sure you want to delete these {0} items?"
    , "Label.RenameItem": "Rename Item"
    , "Message.Prompt.RenameItem": "Enter a new name for the item:"
    , "Message.Error.InvalidFileName": "A file or folder name can not contain any of the following characters:"
    , "Label.CreateFolder": "Create Folder"
    , "Message.Prompt.CreateFolder": "Enter a name for the new folder:"
    , "Label.AddItemsToZip": "Add Items to Zip"
    , "Message.Prompt.AddItemsToZip": "Enter a name for the zip file:"
    , "Label.ExtractItemsFromArchive": "Extract Items From Archive"
    , "Message.Prompt.ExtractItemsFromArchive": "Enter a folder name to extract the archive file to:"
    , "Label.Choose": "Choose"
    , "Label.FolderType": "File Folder"
    , "Label.FileType": "{0} File"
    , "Label.File": "File"
    , "Label.Column.Name": "Name"
    , "Label.Column.DateModified": "Date modified"
    , "Label.Column.Type": "Type"
    , "Label.Column.Size": "Size"
    , "Label.ByteSizeUnit.Bytes": "{0} bytes"
    , "Label.ByteSizeUnit.KB": "{0} KB"
    , "Label.ByteSizeUnit.MB": "{0} MB"
    , "Label.ByteSizeUnit.GB": "{0} GB"
    , "Label.ByteSizeUnit.TB": "{0} TB"
    , "Message.EmptyFolder": "This folder is empty."
    , "Message.NoRootFolders": "No root folders defined."
    , "Message.Error.FileNotAllowed": "The file '{0}' is not allowed."
    , "Label.Info.AllowedFileTypes": "Allowed file types: {0}"
    , "Label.Info.DeniedFileTypes": "Denied file types: {0}"
    , "Message.Error.FolderNotAllowed": "The folder '{0}' is not allowed."
    , "Message.Error.CannotDiscoverPath": "The path '{0}' cannot be discovered."
    , "Message.Error.AccessToPathDenied": "Access to the path '{0}' is denied."
    , "Label.Info.RequiredPermissions": "Required permissions: {0}"
    , "Label.Info.RequiredPermissionsAny": "Required permissions (any): {0}"
    , "Message.Error.QuotaExceeded": "Quota is exceeded for the folder '{0}'."
    , "Label.Info.DeniedFile": "Denied file: {0}"
    , "Label.Info.DeniedSize": "Denied size: {0}"
    , "Label.Info.Limit": "Limit: {0}"
    , "Label.Info.Remaining": "Remaining: {0}"
    , "Message.Error.MaxArchiveSizeExceeded": "The archive '{0}' exceeds the maximum allowed size."
    , "Label.MediaFormatError": "Media Format Error"
    , "Message.Error.MediaFormatError": "Media player could not play this media format on this browser. Would you like to try opening the file directly?"
    , "Label.MediaPlayer": "Media Player"
    , "Label.DocumentViewer": "Document Viewer"
    , "Label.ImageViewer": "Image Viewer"
    , "Label.CopyTo": "Copy to {0}"
    , "Label.MoveTo": "Move to {0}"
    , "Label.UploadTo": "Upload to {0}"
    , "Label.UploadFiles": "Upload Files"
    , "Message.FileConflict": "There is already a file with the same name in this location."
    , "Message.FileConflictAction": "Click the file you want to keep"
    , "Label.FileConflictReplace": "Replace"
    , "Message.FileConflictReplace": "Replace the file in the destination folder with the new file:"
    , "Label.FileConflictSkip": "Skip"
    , "Message.FileConflictSkip": "No files will be changed. Leave this file in the destination folder:"
    , "Label.FileConflictKeepBoth": "Keep both"
    , "Message.FileConflictKeepBoth": "The new file will be renamed:"
    , "Message.FileConflictSameForNext": "Do this for the next {0} conflicts"
    , "Message.FileConflictSameForAll": "Do this for all conflicts"
    , "Label.RefreshPage": "Refresh Page"
    , "Message.SessionExpiredRefresh": "Session has expired, the page will be automatically refreshed in {0} seconds."
    , "Label.ActionCanceled": "Action Canceled"
    , "Message.SelectToUpload": "Select files to be uploaded"
    , "Message.UploadInProgress": "Upload is in progress"
    , "Label.AddFiles": "Add files..."
    , "Label.AddFolders": "Add folders..."
    , "Label.Remove": "Remove"
    , "Label.Clear": "Clear"
    , "Message.DragAndDrop": "Drag and drop files and folders here."
    , "Label.SpecificFiles": "Specific Files ({0})"
    , "Message.Error.SpecificUploadMethod": "Could not load upload method \"{0}\" on this browser ({1})."
    , "Message.Error.AnyUploadMethod": "Could not load any of the specified upload methods \"{0}\" on this browser ({1})."
    , "Label.UploadMethod": "Upload method"
    , "Label.AddToUploadQueue": "Add to the upload queue"
    , "Message.DropNotRecognized": "Dropped item(s) are not recognized. For example this browser ({0}) may support dropping only files but not folders. If you need to drop folders, you can try with another recent browser."
    , "Label.ViewInfo": "View info"
    , "Label.AddConflict": "Add Conflict"
    , "Message.Error.ItemsAlreadyAdded": "The following items with same names were already added to the upload queue."
    , "Message.Error.ItemsFileTypeNotAllowed": "The following items are not allowed to be uploaded due to file type restriction."
    , "Message.Error.ItemsFileSizeNotAllowed": "The following items are not allowed to be uploaded due to file size restriction."
    , "Label.Info.AllowedMaxFileSize": "Allowed maximum file size: {0}"
    , "Label.UploadConflict": "Upload Conflict"
    , "Label.Column.Status": "Status"
    , "Label.Status.Pending": "Pending"
    , "Label.Status.Rejected": "Rejected"
    , "Label.Status.Skipped": "Skipped"
    , "Label.Status.Canceled": "Canceled"
    , "Label.Status.Failed": "Failed"
    , "Label.Status.Completed": "Completed"
    , "Label.ViewStatusReason": "Click to view status reason"
    , "Label.TimeRemaining": "Time remaining"
    , "Label.ItemsRemaining": "Items remaining"
    , "Label.Speed": "Speed"
    , "Label.TimeEstimate": "About {0}"
    , "Label.TimeEstimateHours": "{0} hours"
    , "Label.TimeEstimateMinutes": "{0} minutes"
    , "Label.TimeEstimateSeconds": "{0} seconds"
    , "Label.SpeedEstimate": "{0}/second"
    , "Label.Calculating": "Calculating..."
    , "Message.Confirm.UploadStillInProgress": "Upload is still in progress, are you sure you want to leave?"
    , "Label.CancelAll": "Cancel all"
    , "FileManager.Label.Folders": "Folders"
    , "FileManager.Label.Subfolders": "{0} subfolders"
    , "FileManager.Label.Files": "{0} files"
    , "FileManager.Label.FolderUnavailable": "This folder is unavailable."
    , "FileManager.Action.UpOneLevel": "Up One level"
    , "FileManager.Action.CreateNewFolder": "Create New Folder"
    , "FileManager.Action.DownloadFiles": "Download Files"
    , "FileManager.Action.DownloadAsZip": "Download As Zip"
    , "FileManager.Action.OpenWith": "Open With"
    , "FileManager.Action.WebBrowser": "Web Browser"
    , "FileManager.Action.Explore": "Explore"
    , "FileManager.Action.Folder": "Folder"
    , "FileUploader.Label.NotAvailable": "Not Available"
    , "FileUploader.Action.NewUpload": "New Upload"
    , "FileUploader.Error.EmptyFile": "'{0}' is an empty (zero byte) file."
    , "FileUploader.Label.StatusReason": "Status Reason"
};
(function (n) {
    var t;
    t = typeof require != "undefined" && typeof exports != "undefined" && typeof module != "undefined" ? require("globalize") : n.Globalize;
    t.addCultureInfo("en-US", "default", {
        name: "en-US"
        , englishName: "English (United States)"
    })
})(this);
GleamTech.Util.Culture.cultureInfo = Globalize.cultures["en-US"];
